#!/usr/bin/env bash
# Regenerate niri/outputs.kdl from the monitors niri currently sees.
#
# The main config.kdl is portable; everything monitor-specific lives in
# outputs.kdl, which this script writes. Run it inside a niri session, and
# re-run it whenever you plug in, unplug or rearrange monitors.
#
#   ./gen-outputs.sh                 # write ~/.config/niri/outputs.kdl
#   ./gen-outputs.sh -o out.kdl      # write somewhere else
#   ./gen-outputs.sh --stdout        # just print it

set -euo pipefail

dest="${HOME}/.config/niri/outputs.kdl"
to_stdout=0

while [ $# -gt 0 ]; do
    case "$1" in
        -o|--output) dest="$2"; shift 2 ;;
        --stdout)    to_stdout=1; shift ;;
        -h|--help)   sed -n '2,10p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

command -v niri >/dev/null 2>&1 || { echo "niri not found on PATH" >&2; exit 1; }

tmpjson="$(mktemp)"
trap 'rm -f "$tmpjson"' EXIT

if ! niri msg --json outputs > "$tmpjson" 2>/dev/null; then
    echo "Could not talk to niri - are you running inside a niri session?" >&2
    exit 1
fi

render() {
    python3 - "$tmpjson" <<'PYEOF'
import json, sys

with open(sys.argv[1]) as fh:
    data = json.load(fh)

out = []
out.append('// Generated by gen-outputs.sh - re-run it when your monitors change.')
out.append('// Everything else in config.kdl is machine-independent.')
out.append('')

if not data:
    out.append('// niri reported no outputs.')
    print('\n'.join(out))
    sys.exit(0)

# Left-to-right, top-to-bottom, so the file reads like the desk looks.
for name, o in sorted(data.items(), key=lambda kv: (kv[1]['logical']['y'], kv[1]['logical']['x'])):
    lg = o['logical']
    modes = o.get('modes') or []
    idx = o.get('current_mode')

    out.append('// {} {}  serial {}'.format(
        o.get('make', '?'), o.get('model', '?'), o.get('serial', '?')))
    out.append('output "{}" {{'.format(name))

    if idx is not None and 0 <= idx < len(modes):
        m = modes[idx]
        # refresh_rate is in millihertz
        out.append('    mode "{}x{}@{:.3f}"'.format(
            m['width'], m['height'], m['refresh_rate'] / 1000))
    else:
        out.append('    // no current mode reported; niri will pick the preferred one')

    scale = lg['scale']
    out.append('    scale {}'.format(
        int(scale) if float(scale).is_integer() else scale))
    out.append('    transform "{}"'.format(
        str(lg.get('transform', 'Normal')).lower().lstrip('_')))
    out.append('    position x={} y={}'.format(lg['x'], lg['y']))

    if o.get('vrr_enabled'):
        out.append('    variable-refresh-rate')
    elif o.get('vrr_supported'):
        out.append('    // variable-refresh-rate   // supported by this monitor')

    out.append('}')
    out.append('')

print('\n'.join(out))
PYEOF
}

if [ "$to_stdout" -eq 1 ]; then
    render
else
    mkdir -p "$(dirname "$dest")"
    tmpout="$(mktemp)"
    render > "$tmpout"
    mv "$tmpout" "$dest"
    echo "wrote $dest"
    sed 's/^/    /' "$dest"
fi
